### PR TITLE
Updated asm! macro to llvm_asm!

### PR DESCRIPTION
**Pull request by arjanmels**

### CODE REVIEW

**Comment by MabezDev** [comment]
Thanks! I'm getting:

```rust
error: <inline asm>:57:21: error: invalid operand for instruction
        rur     a3, f64r_hi
```
I'm guessing this is what you meant by [this comment](https://github.com/MabezDev/rust-xtensa/pull/31#issuecomment-636327883)? In which case I'll update the submodule now.

**Comment by MabezDev** [comment]
I've updated the submodule in https://github.com/MabezDev/rust-xtensa/pull/33 . Waiting to build now.

**Comment by arjanmels** [comment]
@MabezDev 
> Thanks! I'm getting:
> 
> ```rust
> error: <inline asm>:57:21: error: invalid operand for instruction
>         rur     a3, f64r_hi
> ```
> 
> I'm guessing this is what you meant by [this comment](https://github.com/MabezDev/rust-xtensa/pull/31#issuecomment-636327883)? In which case I'll update the submodule now.

Indeed by [that comment](https://github.com/MabezDev/rust-xtensa/pull/31#issuecomment-636327883) and [this issue](https://github.com/MabezDev/rust-xtensa/issues/30)

**Comment by MabezDev** [comment]
Perfect! I've updated the fork and this builds!

With this merged, do you think its time to publish the first version on crates.io? 
Would you also like me to publish esp32 now that the interrupt stuff is merged?

**Comment by arjanmels** [comment]
I think there is a solid basis, but I don't know how much work publishing is. There may still crop up additions for the timers (access to the ccompare registers etc.). Same for esp32, there will crop up changes for new peripherals.

**Comment by MabezDev** [comment]
Releases for a crate as simple (i.e no weird build processes) as this one its a breeze. It should simplify the dependencies once its released.

**Comment by MabezDev** [comment]
This crate is now has a v0.1.0 release! https://crates.io/crates/xtensa-lx6-rt

**Pull request merged**
