### PR TITLE
Exception & Interrupt implementation

### PR DESCRIPTION
**Pull request by arjanmels**
This pull request implements exception & interrupt handling.
It introduces a #[interrupt] and #[exception] attribute to facilitate this.

Additionally:
- Improvements in the various assembly functions to use generic functions
- Added functions to trigger interrupts and debug breakpoints

It is based on #10 and makes #6 obsolete.

Next step is to implement higher level interrupt handling in esp32-hal crate.

### CODE REVIEW

**Comment by arjanmels** [comment]
Still doing some finetuning. I changed it back to [WIP] so please do not merge yet.

**Comment by arjanmels** [comment]
Ready for merge now, together with pull requests: https://github.com/esp-rs/esp32/pull/31 and https://github.com/esp-rs/esp32-hal/pull/24.

**Comment by MabezDev** [comment]
Hi @arjanmels I've been trying to test this but I ran into https://github.com/rust-osdev/cargo-xbuild/pull/75 which meant I couldn't build the project because cargo xbuild was pulling the latest version. Instead of working around that, I've made https://github.com/MabezDev/rust-xtensa/pull/31 to update the current fork. Your PR's will no longer build on this version as the `asm!` macro as been renamed to `llvm_asm!`, when you get the time, could you try out the new fork and update your PR's to work with it? I *think* it should be as simple as doing a global find and replace of `asm!` for `llvm_asm!`

**Comment by arjanmels** [comment]
Ok, will look into it this weekend.

**Comment by arjanmels** [comment]
@MabezDev See #13. I hope you get round to testing and pulling. (It is getting a bit messy with all the pull requests which depend on each other.)

**Pull request merged**
